module.exports = {
    CLEAR_STATE_USER_SETTINGS: "CLEAR_STATE_USER_SETTINGS",
    LOGIN_FAIL: "LOGIN_FAIL",
    LOGIN_SUCCESS: "LOGIN_SUCCESS",
    LOGIN_SUCCESS_ADDRESS: "LOGIN_SUCCESS_ADDRESS",
    TOGGLE_ADMIN_SIDEBAR: "TOGGLE_ADMIN_SIDEBAR",
    UPDATE_INPUT: "UPDATE_INPUT",
    UPDATE_INPUT_LOGIN: "UPDATE_INPUT_LOGIN",
    UPDATE_INPUT_REGISTER: "UPDATE_INPUT_REGISTER",
    UPDATE_INPUT_USER_SETTINGS: "UPDATE_INPUT_USER_SETTINGS",
    UPDATE_LOGIN_ADDRESS: "UPDATE_LOGIN_ADDRESS"
};
